controllers/RepliesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\replies\RepliesRecord;
use app\models\replies\RepliesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\topics\TopicsRecord;

/**
 * RepliesController implements the CRUD actions for RepliesRecord model.
 */
class RepliesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all RepliesRecord models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RepliesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single RepliesRecord model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id)
        ]);
    }

    /**
     * Creates a new Reply to an existing Topic.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param integer $topic_id 
     * @return mixed
     */
    public function actionCreate( $topic)
    {
    	//check if topic exists
    	if( TopicsRecord::find()->where([ 'id' => $topic ])->exists() ){
    
	    	$model = new RepliesRecord();
	        
	        
	        if ($model->load(Yii::$app->request->post()) && $model->save()) {
	            return true;
	        } else {
	            return $this->renderAjax('create', [
	                'model' => $model,
	            ]);
	        }
    	} 
    }

    /**
     * Updates an existing RepliesRecord model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing RepliesRecord model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the RepliesRecord model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return RepliesRecord the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = RepliesRecord::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
}

controllers/TopicsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\topics\TopicsRecord;
use app\models\topics\TopicsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * TopicsController implements the CRUD actions for TopicsRecord model.
 */
class TopicsController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        	'access' => [
        		// TODO: nva implement (proper) access control
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create'],
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all TopicsRecord models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TopicsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TopicsRecord model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
    	$topic = $this->findModel($id);
    	$replies = $topic->getReplies()->orderBy('created_at DESC')->all();
    	
        return $this->render('view', [
            'model' => $topic,
        	'author' => $topic->getCreatedBy()->one(),
        	'replies' => $replies
        ]);
    }

    /**
     * Creates a new TopicsRecord model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TopicsRecord();
        
        if ($model->load(Yii::$app->request->post()) && $model->save() ) {
        	    return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing TopicsRecord model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing TopicsRecord model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TopicsRecord model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TopicsRecord the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TopicsRecord::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/topics/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\topics\TopicsRecord */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="topics-record-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'is_api')->hiddenInput([ 'value' => false ] )->label(false); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/topics/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\topics\TopicsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="topics-record-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'content') ?>

    <?= //$form->field($model, 'latest_answer') ?>

    <?= $form->field($model, 'answer_count') ?>

    <?php // echo $form->field($model, 'is_api') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/topics/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\topics\TopicsRecord */

$this->title = Yii::t('app', 'Create New Topic');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Topics'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="topics-record-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/topics/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\topics\TopicsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Topics List');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="topics-record-index">

    <h1><?= Html::encode($this->title) ?></h1>
    
    <?php //echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Topic'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

	<?php //echo '<pre>' ; var_dump($searchModel); echo '</pre>'; exit; ?> 

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            //'id',
            [
            	'attribute' => 'title',
            	'format' => 'html',
            	'value' => function($data){ return Html::a($data->title, ['topics/view', 'id' => $data->id] ); },
            ],
            //'content:ntext',
            [
           		'attribute' => 'latest_answer',
            	'filter' => false
	        ],
			[
        		'attribute' => 'answer_count',
        		'filter' => false
			],
        	[
        		'attribute' => 'is_api',
        		'value' => function($data){ return $data->is_api ? 'Yes' : 'No'; },
        		'filter' => false
    		],
            // 'created_at',
            [
            	'attribute' => 'created_by',
            	'value' => function($data){ return $data['createdBy']->username; },
            	'filter' => false        
            ],
            [
            		'class' => 'yii\grid\ActionColumn',
            		'template' => '{view}'
    		],
        ],
    ]); ?>

</div>

views/topics/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\topics\TopicsRecord */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Topics Record',
]) . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Topics Records'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="topics-record-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/topics/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\topics\TopicsRecord */
/* @var $reply app\models\replies\RepliesRecord */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Topics Records'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="topics-record-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php ////echo Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= 
    			
    			Html::button( Yii::t('app', 'Reply'), [
	            	'class' => 'btn btn-success modal_button',
    				'value' => Url::to(['replies/create', 'topic' => $model->id])
    			]);
    		?>
        <?php /* echo Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) */?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'content:ntext',
            'latest_answer',
            'answer_count',
            [
            	'attribute' => 'is_api',
            	'value' => $model->is_api ? 'Yes' : 'No',
    		],
            'created_at',
            [
            	'attribute' => 'created_by',
            	'format'=> 'raw',
            	'value' => $author->username,
            ],
        ],
    ]) ?>
    
    <h3>Replies</h3>
    
    <!-- Replies Section -->
    
    <div class="container">
    	<div class="row">
    	<?php Pjax::begin(['id' => 'replies_container']);?>
    	<?php if( count($replies) < 1 ): ?>
    		
    		<p><?= Yii::t('app', 'No messages yet.'); ?></p>
    		
    		<?= 
    			
    			Html::button( Yii::t('app', 'Be the first to reply to this'), [
	            	'class' => 'btn btn-default modal_button',
    				'value' => Url::to(['replies/create', 'topic' => $model->id])
    			]);
    		?>
    	
    	<?php else:?>
		    <?php foreach( $replies as $r ): ?>
		    	
		    	<div class="panel panel-default">
					<div class="panel-heading">
						
						<strong><?= $r->title; ?></strong>
						<small>
						<?= 
							$r->getCreatedBy()->one()->username .' '.
							Yii::t('app', 'on') .' '. $r->created_at .' '.
							Yii::t('app', 'via') .' '. ($r->is_api ? 'Api' : 'Web') 
						?>
						</small>
						
					</div>
			  		<div class="panel-body">
			    		<?= $r->content; ?>
			  		</div>
				</div>
		    	
		    <?php endforeach;?>
		    
		
		<?php endif;?>
		<?php Pjax::end();?>
		
		<?php 
		/* 
		**
		* Modal form for replying to topic
		**
		*/
			Modal::begin([
					'header' => 'Place your reply',
					'id' => 'modal',
					'size' => 'modal-md'
			]);
		?>
		
		<div id="modal_content" data-topic="<?= $model->id; ?>"></div>
		
		<?php Modal::end()?>
		
		</div>
    </div>
</div>